services:
  - type: web
    name: ssdj-app
    runtime: php
    runtimeVersion: 8.2
    buildCommand: composer install && php artisan migrate --force
    startCommand: vendor/bin/heroku-php-apache2 public/
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: ssdj-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: ssdj-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: ssdj-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: ssdj-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: ssdj-db
          property: password
      - key: LOG_CHANNEL
        value: stack

  - type: mysql
    name: ssdj-db
    ipAllowList: []
    plan: free
